# Collections
### Michiel Stock, Bram De Jaegher, Daan Van Hauwermeiren
### 2019-2020
# Arrays
Let us start with `Array`s. It is very similar to lists in Python, though it can have more than one dimension. An `Array` is defined as follows,

In [1]:
A = []            # empty array

Any[]

In [2]:
X = [1, 3, -5, 7] # array of integers

4-element Array{Int64,1}:
  1
  3
 -5
  7

In [3]:
y = [1, "2", [1, 2, 3]]   # the element can be different

3-element Array{Any,1}:
 1
  "2"
  [1, 2, 3]

## Indexing and slicing
Let's start by eating the frog. Julia uses 1-based indexing...

In [4]:
names = ["Arthur", "Ford", "Zaphod", "Marvin", "Trillian", "Eddie"]

6-element Array{String,1}:
 "Arthur"
 "Ford"
 "Zaphod"
 "Marvin"
 "Trillian"
 "Eddie"

In [5]:
names[0]        # this does not work, sorry Python is OK, for julia from 1

LoadError: BoundsError: attempt to access 6-element Array{String,1} at index [0]

In [6]:
names[1]        # hell yeah!

"Arthur"

In [7]:
names[end]      # last element

"Eddie"

In [8]:
names[end-1]    # second to last element

"Trillian"

Slicing arrays is intuitive,

In [9]:
names[3:6]    # index using slides

4-element Array{String,1}:
 "Zaphod"
 "Marvin"
 "Trillian"
 "Eddie"

and slicing with assignment too.

In [10]:
names[end-1:end] = ["Slartibartfast","The Whale and the Bowl of Petunias"]    # assign a value, mutable

2-element Array{String,1}:
 "Slartibartfast"
 "The Whale and the Bowl of Petunias"

In [11]:
names

6-element Array{String,1}:
 "Arthur"
 "Ford"
 "Zaphod"
 "Marvin"
 "Slartibartfast"
 "The Whale and the Bowl of Petunias"

## Types
Julia arrays can be of mixed type.

In [12]:
Y = [42, "Universe", []]

3-element Array{Any,1}:
 42
   "Universe"
   Any[]

The type of the array changes depending on the elements that make up the array.

In [13]:
typeof(A)

Array{Any,1}

In [14]:
typeof(X)

Array{Int64,1}

In [15]:
typeof(Y)

Array{Any,1}

When the elements of the arrays are mixed, the type is promoted to the closest common ancestor. For `Y` this is `Any`.  But an array of an integer and a float becomes an...

In [16]:
B = [1.1, 1]   # the type of the array
typeof(B)     # type of array

Array{Float64,1}

In [18]:
eltype(B)   # gives the type of the elements

Float64

... array of floats.

Julia allows the flexibility of having mixed types, though this will hinder performance, as the compiler can no longer optimize for the type. If you process an array of `Any`s, your code will be as slow as Python.

To create an array of a particular type, just use `Type[]`.

In [19]:
Float64[1, 2, 3]    # float too change the type of the element

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [21]:
Float64[1, 2, 3, 'a']     # char changed to number

4-element Array{Float64,1}:
  1.0
  2.0
  3.0
 97.0

In [22]:
Float(Float64[1, 2, 3, "A"])    # error

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

## Initialisation
Arrays can be initialized in all the classic, very Pythonesque ways.

In [23]:
C = []  # empty

zeros(5)      # row vector of 5 zeroes, give the initialized of the array, one elenet is array, 1-Dim

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [24]:
ones(3,3)     # 3X3 matrix of 1's, will be discussed later on, 2-Dim

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [26]:
ones(3, 3, 3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [25]:
fill(0.5, 10) # in case you want to fill a matrix with a specific value --- function fill 

10-element Array{Float64,1}:
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5

In [28]:
fill(1, (2, 3))   # this is also works

2×3 Array{Int64,2}:
 1  1  1
 1  1  1

In [27]:
?fill

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims::Tuple)
fill(x, dims...)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

`dims` may be specified as either a tuple or a sequence of arguments. For example, the common idiom `fill(x)` creates a zero-dimensional array containing the single value `x`.

# Examples

```jldoctest
julia> fill(1.0, (2,3))
2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> fill(42)
0-dimensional Array{Int64,0}:
42
```

If `x` is an object reference, all elements will refer to the same object:

```jldoctest
julia> A = fill(zeros(2), 2);

julia> A[1][1] = 42; # modifies both A[1][1] and A[2][1]

julia> A
2-element Array{Array{Float64,1},1}:
 [42.0, 0.0]
 [42.0, 0.0]
```


In [29]:
rand(2)    # row vector of 2 random floats [0,1], 

2-element Array{Float64,1}:
 0.863172660589494
 0.6062212129590732

In [30]:
randn(2)   # same but normally-distributed random numbers

2-element Array{Float64,1}:
  0.9914085257256149
 -0.2008523719193169

Sometimes it is better to provide a specific type for initialization. `Float64` is often the default.

In [31]:
zeros(Int8, 5)

5-element Array{Int8,1}:
 0
 0
 0
 0
 0

## Comprehensions and list-like operations

Comprehensions are a concise and powerful way to construct arrays and are very loved by the Python community.

In [33]:
Y = [1, 2, 3, 4, 5, 6, 8, 9, 8, 6, 5, 4, 3, 2, 1]
t = 0.1
dY = [Y[i-1] - 2*Y[i] + Y[i+1] for i=2:length(Y)-1]         # central difference

13-element Array{Int64,1}:
  0
  0
  0
  0
  1
 -1
 -2
 -1
  1
  0
  0
  0
  0

General $N$-dimensional arrays can be constructed using the following syntax:

```
[ F(x,y,...) for x=rx, y=ry, ... ]
```

Note that this is similar to using set notation. For example:

In [34]:
[i * j for i in 1:4, j in 1:5]   # notice the usage here-- comprehension 

4×5 Array{Int64,2}:
 1  2   3   4   5
 2  4   6   8  10
 3  6   9  12  15
 4  8  12  16  20

## Pushing, appending and popping

Arrays behave like a stack. Elements can be added to the back of the array,

In [35]:
push!(names, "Eddie") # add a single element, liist first, only one element

7-element Array{String,1}:
 "Arthur"
 "Ford"
 "Zaphod"
 "Marvin"
 "Slartibartfast"
 "The Whale and the Bowl of Petunias"
 "Eddie"

In [36]:
append!(names, ["Sam", "Gerard"]) # add an array , can be a list also one element

9-element Array{String,1}:
 "Arthur"
 "Ford"
 "Zaphod"
 "Marvin"
 "Slartibartfast"
 "The Whale and the Bowl of Petunias"
 "Eddie"
 "Sam"
 "Gerard"

"Eddie" was appended as the final element of the Array along with "Sam" and "Gerard". Remember, a "!" is used to indicate an in-place function. `pop()` is used to return and remove the final element of an array

In [37]:
pop!(names)    # pop the last elements

"Gerard"

In [43]:
? pop!

search: pop! popat! popfirst! setproperty! partialsortperm! popdisplay



```
pop!(collection) -> item
```

Remove an item in `collection` and return it. If `collection` is an ordered container, the last item is returned.

# Examples

```jldoctest
julia> A=[1, 2, 3]
3-element Array{Int64,1}:
 1
 2
 3

julia> pop!(A)
3

julia> A
2-element Array{Int64,1}:
 1
 2

julia> S = Set([1, 2])
Set{Int64} with 2 elements:
  2
  1

julia> pop!(S)
2

julia> S
Set{Int64} with 1 element:
  1

julia> pop!(Dict(1=>2))
1 => 2
```

---

```
pop!(collection, key[, default])
```

Delete and return the mapping for `key` if it exists in `collection`, otherwise return `default`, or throw an error if `default` is not specified.

# Examples

```jldoctest
julia> d = Dict("a"=>1, "b"=>2, "c"=>3);

julia> pop!(d, "a")
1

julia> pop!(d, "d")
ERROR: KeyError: key "d" not found
Stacktrace:
[...]

julia> pop!(d, "e", 4)
4
```


# Matrices

Let's add a dimension and go to 2D Arrays, matrices. It is all quite straightforward,

In [44]:
Z = [0 1 1; 2 3 5; 8 13 21; 34 55 89]     # the element in one row has no , or sth

4×3 Array{Int64,2}:
  0   1   1
  2   3   5
  8  13  21
 34  55  89

In [46]:
Z[3,2]  # indexing, row, col

13

In [47]:
Z[1,:]  # slicing

3-element Array{Int64,1}:
 0
 1
 1

It is important to know that arrays and other collections are copied by reference.

In [48]:
R = Z

4×3 Array{Int64,2}:
  0   1   1
  2   3   5
  8  13  21
 34  55  89

In [49]:
Z

4×3 Array{Int64,2}:
  0   1   1
  2   3   5
  8  13  21
 34  55  89

In [50]:
R

4×3 Array{Int64,2}:
  0   1   1
  2   3   5
  8  13  21
 34  55  89

In [51]:
R[1,1] = 42    # matrix are mutable

42

In [52]:
Z

4×3 Array{Int64,2}:
 42   1   1
  2   3   5
  8  13  21
 34  55  89

`deepcopy()` can be used to make a wholly dereferenced object.

## Concatenation -- matrix
Arrays can be constructed and also concatenated using the following functions,

In [54]:
Z = [0 1 1; 2 3 5; 8 13 21; 34 55 89]
Y = rand(4,3)

4×3 Array{Float64,2}:
 0.317012  0.306939  0.147653
 0.458407  0.423985  0.146204
 0.642066  0.859671  0.295426
 0.379009  0.561802  0.0644774

In [55]:
cat(Z, Y, dims=2)                # concatenation along a specified dimension

4×6 Array{Float64,2}:
  0.0   1.0   1.0  0.317012  0.306939  0.147653
  2.0   3.0   5.0  0.458407  0.423985  0.146204
  8.0  13.0  21.0  0.642066  0.859671  0.295426
 34.0  55.0  89.0  0.379009  0.561802  0.0644774

In [56]:
cat(Z, Y, dims=1) == vcat(Z,Y) == [Z;Y]   # vertical concatenation

true

In [57]:
cat(Z,Y,dims=2) == hcat(Z,Y) == [Z Y]   # horizontal concatenation

true

Note that `;` is an operator to use `vcat`, e.g.

In [58]:
[zeros(2, 2) ones(2, 1); ones(1, 3)]   # be familiar with the application

3×3 Array{Float64,2}:
 0.0  0.0  1.0
 0.0  0.0  1.0
 1.0  1.0  1.0

This simplified syntax can lead to strange behaviour. Explain the following difference.

In [59]:
[1  2-3]

1×2 Array{Int64,2}:
 1  -1

In [60]:
[1 2 -3]

1×3 Array{Int64,2}:
 1  2  -3

Sometimes, `vcat` and `hcat` are better used to make the code unambiguous.

## Vector operations

By default, the `*` operator is used for matrix-matrix multiplication

In [61]:
A = [2 4 3; 3 1 5]  # * for matrix multiplication
B = [ 3 10; 4 1 ;7 1]

A * B

2×2 Array{Int64,2}:
 43  27
 48  36

This is the Julia way since functions act on the objects, and element-wise operatios are done with "dot" operations. For every function or binary operation like `^` there is a "dot" operation `.^` to perform element-by-element exponentiation on arrays.

In [62]:
Y = [10 10 10; 20 20 20]
Y.^2

2×3 Array{Int64,2}:
 100  100  100
 400  400  400

Under the hood, Julia is looping over the elements of `Y`. So a sequence of dot-operations is fused into a single loop.

In [63]:
Y.^2 .+ cos.(Y)

2×3 Array{Float64,2}:
  99.1609   99.1609   99.1609
 400.408   400.408   400.408

Did you notice that dot-operations are also applicable to functions, even user-defined functions? As programmers, we are by lazy by definition and all these dots are a lot of work. The `@.` macro does this for us.

In [64]:
Y.^2 .+ cos.(Y) == @. Y^2 + cos(Y)   # if both the operator has ̇ operator ---- 

true

### notice @\dot operator

# Higher dimensional arrays

Matrices can be generalized to multiple dimensions.

In [65]:
X = rand(3, 3, 3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 0.773593  0.616138  0.586154
 0.941792  0.504142  0.611366
 0.387747  0.809517  0.284013

[:, :, 2] =
 0.814807  0.243749  0.874876
 0.632562  0.312171  0.592685
 0.677111  0.429598  0.377468

[:, :, 3] =
 0.299212  0.0436128  0.0366284
 0.879391  0.5611     0.405849
 0.374575  0.607182   0.664727

# Ranges

The colon operator `:` can be used to construct unit ranges, e.g., from 1 to 20:

In [66]:
ur = 1:20

1:20

Or by increasing in steps:

In [68]:
str = 1:3:20   # 3 is the steps

1:3:19

Similar to the `range` function in Python, the object that is created is not an array, but an iterator. This is actually the term used in Python. Julia has many different types and structs, which behave a particular way. Types of `UnitRange` only store the beginning and end value (and stepsize in the case of `StepRange`). But functions are overloaded such that it acts as arrays.

In [73]:
for i in ur    # give all the value from 1 to 20
  println(i)
end

str[3]         # is 7, as step is 3

length(str)      # is 7

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


7

All values can be obtained using `collect`:

In [74]:
collect(str)           # 

7-element Array{Int64,1}:
  1
  4
  7
 10
 13
 16
 19

In [75]:
?collect   # give all items in a collectioons or iterators


search: collect



```
collect(element_type, collection)
```

Return an `Array` with the given element type of all items in a collection or iterable. The result has the same shape and number of dimensions as `collection`.

# Examples

```jldoctest
julia> collect(Float64, 1:2:5)
3-element Array{Float64,1}:
 1.0
 3.0
 5.0
```

---

```
collect(collection)
```

Return an `Array` of all items in a collection or iterator. For dictionaries, returns `Pair{KeyType, ValType}`. If the argument is array-like or is an iterator with the [`HasShape`](@ref IteratorSize) trait, the result will have the same shape and number of dimensions as the argument.

# Examples

```jldoctest
julia> collect(1:2:13)
7-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13
```


Such implicit objects can be processed much smarter than naive structures. Compare!

In [76]:
@time sum((i for i in 1:100_000_000))

  0.000000 seconds


5000000050000000

In [77]:
@time sum(1:100_000_000)

  0.000000 seconds


5000000050000000

`StepRange` and `UnitRange` also work with floats.

In [78]:
0:0.1:10

0.0:0.1:10.0

# Other collections

Some of the other collections include tuples, dictionaries, and others.

In [79]:
tupleware = ("tuple", "ware") # tuples

("tuple", "ware")

In [80]:
scores = Dict("humans" => 2, "vogons" => 1) # dictionaries

Dict{String,Int64} with 2 entries:
  "humans" => 2
  "vogons" => 1

In [81]:
scores["humans"]

2

# Exercises

## Vandermonde matrix

Write a function to generate an $n \times m$ [Vandermonde matrix](https://en.wikipedia.org/wiki/Vandermonde_matrix) for a given vector $\alpha=[\alpha_1,\alpha_2,\ldots,\alpha_m]^T$. This matrix is defined as follows

$$
{\displaystyle V={\begin{bmatrix}1&\alpha _{1}&\alpha _{1}^{2}&\dots &\alpha _{1}^{n-1}\\1&\alpha _{2}&\alpha _{2}^{2}&\dots &\alpha _{2}^{n-1}\\1&\alpha _{3}&\alpha _{3}^{2}&\dots &\alpha _{3}^{n-1}\\\vdots &\vdots &\vdots &\ddots &\vdots \\1&\alpha _{m}&\alpha _{m}^{2}&\dots &\alpha _{m}^{n-1}\end{bmatrix}},}
$$

or

$$
V = [\alpha_i^{j-1}] .
$$

Write a one-liner function `vandermonde` to generate this matrix. This function takes as a vector `α` and `m`, the number of powers to compute.

In [ ]:
vandermonde(α, m) = ...

## Determinant

Write a function `mydet` to compute the determinant of a square matrix. Remember, for a $2 \times 2$ matrix, the determinant is computed as

$$
{\displaystyle|A|={\begin{vmatrix}a&b\\c&d\end{vmatrix}}=ad-bc.}
$$


For larger matrices, there is a recursive way of computing the determinant based on the minors, i.e. the determinants of the submatrices. See [http://mathworld.wolfram.com/Determinant.html](http://mathworld.wolfram.com/Determinant.html).

Write a function to compute the determinant of a general square matrix.

In [ ]:
function mydet(A)
  size(A,1) != size(A,2) && throw(DimensionMismatch)
  ...
end

## Ridge regression

Ridge regression can be seen as an extension of ordinary least squares regression,

$$\beta X =b\, ,$$

where a matrix $\beta$ is sought which minimizes the sum of squared residuals between the model and the observations,

$$SSE(\beta) = (y - \beta X)^T (y - \beta X)$$

In some cases it is adviceable to add a regularisation term to this objective function,

$$SSE(\beta) = (y - \beta X)^T (y - \beta X) + \lambda \left\lVert X \right\rVert^2_2 \, , $$

this is known as ridge regression. The matrix $\beta$ that minimises the objective function can be computed analytically.

$$\beta = \left(X^T X + \lambda I \right)^{-1}X^T y$$

Let us look at an example. We found some data on the evolution of human and dolphin intelligence.

In [ ]:
using Plots

blue = "#8DC0FF"
red = "#FFAEA6"

t = collect(0:10:3040)
ϵ₁ = randn(length(t))*15     # noise on Dolphin IQ
ϵ₂ = randn(length(t))*20     # noise on Human IQ

Y₁ = dolphinsIQ = t/12 + ϵ₁
Y₂ = humanIQ = t/20 + ϵ₂

scatter(t,Y₁; label="Dolphins", color=blue,
  ylabel="IQ (-)", xlabel ="Time (year BC)", legend=:topleft)
scatter!(t,Y₂; label="Humans", color=red)

> "For instance, on the planet Earth, man had always assumed that he was more intelligent than dolphins because he had achieved so much - the wheel, New York, wars and so on - whilst all the dolphins had ever  done was muck about in the water having a good time. But conversely, the dolphins had always believed that they were far more intelligent than man - for precisely the same reasons."
>
> *Hitchhikers guide to the galaxy*

**Assignment:** Plot the trend of human vs. dolphin intelligence by implementing the analytical solution for ridge regression. For this, you need the uniform scaling operator `I`, found in the `LinearAlgebra` package. Use $\lambda=0.01$.

In [ ]:
using LinearAlgebra

β₁ = #...
β₂ = #...

Y₁ = β₁*t
Y₂ = β₂*t

# References
- [Julia Documentation](https://juliadocs.github.io/Julia-Cheat-Sheet/)
- [Introduction to Julia UCI data science initiative](http://ucidatascienceinitiative.github.io/IntroToJulia/)
- [Month of Julia](https://github.com/DataWookie/MonthOfJulia)
- [Why I love Julia, Next Journal](https://nextjournal.com/kolia/why-i-love-julia)